### ISSUE TITLE
Integration on Website

### ISSUE THREAD

**Issue by Tacitus2k** [mavrosxristoforos/chatgpt-assistant#1]
Your idea is great and with the chatgpt API the chat works good. The main problem is, that the chatbot did not know the content of the website where it is running. So a dynamic integration of the website content might be a good idea? Maybe with a plugin which searches the website and gives the information to the modul?
I'm sorry, but I don't have sufficient programming knowledge; however, this behavior caught my attention during an extensive review of the module.
Best wishes!
Philipp

**Comment by mavrosxristoforos** [comment]
Hello Philipp and thank you for posting.
That is exactly what ChatGPT Assistant Pro will do.
With the use of the OpenAI Assistants API and Files, you can provide custom knowledge and instruct the bot to reply based on your own content.
Please use my website's contact form if you are interested in participating in beta tests.
Thanks again!
